#!/bin/bash
input=$(cat "$1")
host_count_dict={}
while read -r line; do
  host=$(echo "$line" | cut -f1 -d' ')
  if [[ ! -z "$host" ]]; then
    if [[ -z "${host_count_dict[$host]}" ]]; then
      host_count_dict[$host]=0
    fi
    host_count_dict[$host]=$((${host_count_dict[$host]}+1))
  fi
done < "$input"
for host in "${host_count_sorted_list[@]}"; do
  echo "$host"
done | head -11
